language: node_js
node_js:
  - '8'
  - '6'
  - '4'

env:
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=3

install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION || true

script:
  - npm test

after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
